version: '3'

services:
  account-manager:
    image: docker.pkg.github.com/ledgerhq/lama-scheduler/lama-scheduler:${LAMA_VERSION}
    environment:
      JAVA_OPTS: ${ACCOUNT_MANAGER_JAVA_OPTS}
      ACCOUNT_MANAGER_PORT: ${ACCOUNT_MANAGER_PORT}
      ACCOUNT_MANAGER_JDBC_URL: ${ACCOUNT_MANAGER_JDBC_URL}
      ACCOUNT_MANAGER_POSTGRES_USER: ${ACCOUNT_MANAGER_POSTGRES_USER}
      ACCOUNT_MANAGER_POSTGRES_PASSWORD: ${ACCOUNT_MANAGER_POSTGRES_PASSWORD}
      WORKER_EVENTS_EXCHANGE_NAME: ${WORKER_EVENTS_EXCHANGE_NAME}
      LAMA_EVENTS_EXCHANGE_NAME: ${LAMA_EVENTS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_SSL: ${REDIS_SSL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${ACCOUNT_MANAGER_REDIS_DB}
      BITCOIN_SYNC_FREQUENCY: ${BITCOIN_SYNC_FREQUENCY}
      LOG_APPENDER: ${LOG_APPENDER}
      LOG_LEVEL: ${LOG_LEVEL}
      DD_TRACE_ENABLED: "false"
    ports:
      - ${ACCOUNT_MANAGER_PORT}:${ACCOUNT_MANAGER_PORT}
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./tooling/postgres:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 15s
      retries: 10

  redis:
    image: redis:${REDIS_VERSION}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

  bitcoin-lib-grpc:
    image: docker.pkg.github.com/ledgerhq/bitcoin-lib-grpc/bitcoin-lib-grpc:${BITCOIN_LIB_GRPC_VERSION}
    environment:
      BITCOIN_HOST: ${BITCOIN_LIB_GRPC_HOST}
      BITCOIN_PORT: ${BITCOIN_LIB_GRPC_PORT}
    ports:
      - ${BITCOIN_LIB_GRPC_PORT}:${BITCOIN_LIB_GRPC_PORT}

  bitcoin-keychain:
    image: docker.pkg.github.com/ledgerhq/bitcoin-keychain/bitcoin-keychain:${BITCOIN_KEYCHAIN_VERSION}
    environment:
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_LOG_LEVEL: ${BITCOIN_KEYCHAIN_LOG_LEVEL}
      BITCOIN_KEYCHAIN_JSON_LOGS: ${BITCOIN_KEYCHAIN_JSON_LOGS}
      BITCOIN_HOST: ${BITCOIN_LIB_GRPC_HOST}
      BITCOIN_PORT: ${BITCOIN_LIB_GRPC_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL: ${REDIS_SSL}
      REDIS_DB: ${BITCOIN_KEYCHAIN_REDIS_DB}
    depends_on:
      - redis
      - bitcoin-lib-grpc
    ports:
      - ${BITCOIN_KEYCHAIN_PORT}:${BITCOIN_KEYCHAIN_PORT}

  bitcoin-api:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-api:${LAMA_VERSION}
    environment:
      JAVA_OPTS: ${BITCOIN_API_JAVA_OPTS}
      BITCOIN_API_HOST: ${BITCOIN_API_HOST}
      BITCOIN_API_PORT: ${BITCOIN_API_PORT}
      ACCOUNT_MANAGER_HOST: ${ACCOUNT_MANAGER_HOST}
      ACCOUNT_MANAGER_PORT: ${ACCOUNT_MANAGER_PORT}
      ACCOUNT_MANAGER_SSL: ${ACCOUNT_MANAGER_SSL}
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_SSL: ${BITCOIN_KEYCHAIN_SSL}
      BITCOIN_INTERPRETER_HOST: ${BITCOIN_INTERPRETER_HOST}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      BITCOIN_INTERPRETER_SSL: ${BITCOIN_INTERPRETER_SSL}
      BITCOIN_TRANSACTOR_HOST: ${BITCOIN_TRANSACTOR_HOST}
      BITCOIN_TRANSACTOR_PORT: ${BITCOIN_TRANSACTOR_PORT}
      BITCOIN_TRANSACTOR_SSL: ${BITCOIN_TRANSACTOR_SSL}
      BITCOIN_WORKER_HOST: ${BITCOIN_WORKER_HOST}
      BITCOIN_WORKER_PORT: ${BITCOIN_WORKER_PORT}
      BITCOIN_WORKER_SSL: ${BITCOIN_WORKER_SSL}
      LAMA_NOTIFICATIONS_EXCHANGE_NAME: ${LAMA_NOTIFICATIONS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      LOG_APPENDER: ${LOG_APPENDER}
      LOG_LEVEL: ${LOG_LEVEL}
      DD_TRACE_ENABLED: "false"
    ports:
      - ${BITCOIN_API_PORT}:${BITCOIN_API_PORT}
    depends_on:
      - lama-scheduler
      - bitcoin-keychain
      - bitcoin-interpreter
      - bitcoin-worker

  bitcoin-transactor:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-transactor:${LAMA_VERSION}
    environment:
      JAVA_OPTS: ${BITCOIN_TRANSACTOR_JAVA_OPTS}
      BITCOIN_TRANSACTOR_PORT: ${BITCOIN_TRANSACTOR_PORT}
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_SSL: ${BITCOIN_KEYCHAIN_SSL}
      BITCOIN_INTERPRETER_HOST: ${BITCOIN_INTERPRETER_HOST}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      BITCOIN_INTERPRETER_SSL: ${BITCOIN_INTERPRETER_SSL}
      BITCOIN_LIB_GRPC_HOST: ${BITCOIN_LIB_GRPC_HOST}
      BITCOIN_LIB_GRPC_PORT: ${BITCOIN_LIB_GRPC_PORT}
      BITCOIN_LIB_GRPC_SSL: ${BITCOIN_LIB_GRPC_SSL}
      LOG_APPENDER: ${LOG_APPENDER}
      LOG_LEVEL: ${LOG_LEVEL}
      DD_TRACE_ENABLED: "false"
    ports:
      - ${BITCOIN_TRANSACTOR_PORT}:${BITCOIN_TRANSACTOR_PORT}

  bitcoin-interpreter:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-interpreter:${LAMA_VERSION}
    environment:
      JAVA_OPTS: ${BITCOIN_INTERPRETER_JAVA_OPTS}
      BITCOIN_INTERPRETER_JDBC_URL: ${BITCOIN_INTERPRETER_JDBC_URL}
      BITCOIN_INTERPRETER_POSTGRES_USER: ${BITCOIN_INTERPRETER_POSTGRES_USER}
      BITCOIN_INTERPRETER_POSTGRES_PASSWORD: ${BITCOIN_INTERPRETER_POSTGRES_PASSWORD}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      LAMA_NOTIFICATIONS_EXCHANGE_NAME: ${LAMA_NOTIFICATIONS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      BITCOIN_EXPLORER_URI: ${BITCOIN_EXPLORER_URI}
      BITCOIN_EXPLORER_ADDRESSES_SIZE: ${BITCOIN_EXPLORER_ADDRESSES_SIZE}
      BITCOIN_EXPLORER_TXS_BATCH_SIZE: ${BITCOIN_EXPLORER_TXS_BATCH_SIZE}
      BITCOIN_EXPLORER_TIMEOUT: ${BITCOIN_EXPLORER_TIMEOUT}
      LOG_APPENDER: ${LOG_APPENDER}
      LOG_LEVEL: ${LOG_LEVEL}
      DD_TRACE_ENABLED: "false"

    depends_on:
      - postgres
      - rabbitmq
    ports:
      - ${BITCOIN_INTERPRETER_PORT}:${BITCOIN_INTERPRETER_PORT}

  bitcoin-worker:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-worker:${LAMA_VERSION}
    environment:
      JAVA_OPTS: ${BITCOIN_WORKER_JAVA_OPTS}
      BITCOIN_WORKER_PORT: ${BITCOIN_WORKER_PORT}
      WORKER_EVENTS_EXCHANGE_NAME: ${WORKER_EVENTS_EXCHANGE_NAME}
      LAMA_EVENTS_EXCHANGE_NAME: ${LAMA_EVENTS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_SSL: ${BITCOIN_KEYCHAIN_SSL}
      BITCOIN_EXPLORER_URI: ${BITCOIN_EXPLORER_URI}
      BITCOIN_EXPLORER_ADDRESSES_SIZE: ${BITCOIN_EXPLORER_ADDRESSES_SIZE}
      BITCOIN_EXPLORER_TXS_BATCH_SIZE: ${BITCOIN_EXPLORER_TXS_BATCH_SIZE}
      BITCOIN_EXPLORER_TIMEOUT: ${BITCOIN_EXPLORER_TIMEOUT}
      BITCOIN_INTERPRETER_HOST: ${BITCOIN_INTERPRETER_HOST}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      BITCOIN_INTERPRETER_SSL: ${BITCOIN_INTERPRETER_SSL}
      LOG_APPENDER: ${LOG_APPENDER}
      LOG_LEVEL: ${LOG_LEVEL}
      DD_TRACE_ENABLED: "false"
    depends_on:
      - rabbitmq
      - bitcoin-keychain
      - bitcoin-interpreter
    ports:
      - ${BITCOIN_WORKER_PORT}:${BITCOIN_WORKER_PORT}
