name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  unit-tests:
    name: unit-test-${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [accountManager]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .ivy2
            .sbt
          key: lama-docker-cache-${{github.ref}}-${{ hashFiles('build.sbt') }}
          restore-keys: |
            lama-docker-cache-${{github.ref}}-${{ hashFiles('build.sbt') }}
            lama-docker-cache-${{github.ref}}
            lama-docker-cache-
      - name: Run ${{ matrix.component }} unit tests
        run: SBT_OPTS="-Xss512m" sbt -Dsbt.ivy.home=.ivy2 -sbt-dir .sbt ${{ matrix.component }}/test
    env:
      LOG_APPENDER: STDOUT

  it-tests:
    name: it-test-${{ matrix.component }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [accountManager]
    services:
      rabbitmq:
        image: rabbitmq:3.8.5
        env:
          RABBITMQ_DEFAULT_USER: lama
          RABBITMQ_DEFAULT_PASS: serge
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 5s
          --health-timeout 15s
          --health-retries 10
        ports:
          - 5672:5672
      redis:
        image: redis:6.0.6-alpine
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: lama
          POSTGRES_USER: lama
          POSTGRES_PASSWORD: serge
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      POSTGRES_DB: lama
      POSTGRES_USER: lama
      POSTGRES_PASSWORD: serge
      REDIS_PASSWORD: ""
      ACCOUNT_MANAGER_JDBC_URL: jdbc:postgresql:test_lama
      BITCOIN_INTERPRETER_JDBC_URL: jdbc:postgresql:test_lama_btc
      LOG_APPENDER: STDOUT
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .ivy2
            .sbt
          key: lama-docker-cache-${{github.ref}}-${{ hashFiles('build.sbt') }}
          restore-keys: |
            lama-docker-cache-${{github.ref}}-${{ hashFiles('build.sbt') }}
            lama-docker-cache-${{github.ref}}
            lama-docker-cache-
      - name: Install postgresql-client
        run: sudo apt update && sudo apt install -y postgresql-client
      - name: Create dbs
        run: |
          PGPASSWORD=${POSTGRES_PASSWORD} createdb -h localhost -p 5432 -w -U $POSTGRES_USER lama_btc
          PGPASSWORD=${POSTGRES_PASSWORD} createdb -h localhost -p 5432 -w -U $POSTGRES_USER test_lama
          PGPASSWORD=${POSTGRES_PASSWORD} createdb -h localhost -p 5432 -w -U $POSTGRES_USER test_lama_btc
      - name: Run ${{ matrix.component }} it tests
        run: SBT_OPTS="-Xss512m" sbt -Dsbt.ivy.home=.ivy2 -sbt-dir .sbt clean coverage ${{ matrix.component }}/it:test coverageReport

